### ISSUE TITLE
Flicker in prod

### ISSUE THREAD

**Issue by tashburn** [Alex-ray/universal-hmr-ssr-react-redux#2]
Thanks for creating this example -- I'm starting to use it as boilerplate.

However, in prod, when I refresh the browser (Chrome 55, MacOS 10.12.1), I usually see the html content without css styling briefly (a flicker), then I see the proper content with css styling applied.

I don't see this flicker in dev mode.

Any ideas how to remove the prod flicker?

**Comment by Alex-ray** [comment]
Hey @tashburn yup, this is because your CSS hasn't quite downloaded but your HTML is fully rendered in the browser. This causes the brief flicker that you are experiencing, does that make sense?

This is typically referred to as Flash of Unstyled Content of FOUC 

The most common way to fix this is to include a small bit of css embedded into your initial HTML to style the page while the rest of you CSS loads. This is also why you see a lot of website render a small loading screen before you see anything else.

To do this you could pass a simple stylesheet to be inserted into the HTML here https://github.com/Alex-ray/universal-hmr-ssr-react-redux/blob/master/src/server/Html.js 

That way it would be include for every static page!

Here is a little SO thread on it http://stackoverflow.com/questions/3221561/eliminate-flash-of-unstyled-content

**Comment by tashburn** [comment]
Much appreciated!
